import type { Question } from "../../state/mockData";

let _idCounter = 500;
function sq(
  partial: Omit<Question, "id" | "headingId" | "imageAttachment" | "type">,
): Question {
  return {
    id: `starter-${_idCounter++}`,
    headingId: null,
    imageAttachment: null,
    type: "Starter",
    ...partial,
  };
}

// ─── STANDARD 11 ───────────────────────────────────────────────────────────
export const std11Questions: Question[] = [
  // Science - Physics
  sq({
    text: "A particle moves in a circle of radius 2 m with speed 4 m/s. Find its centripetal acceleration.",
    questionType: "numerical",
    marks: 3,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Science",
    chapter: "Laws of Motion",
    difficulty: "medium",
    tags: ["circular-motion", "centripetal"],
    answer: "a = v²/r = 16/2 = 8 m/s²",
    numericalData: { unit: "m/s²" },
  }),
  sq({
    text: "State and explain the First Law of Thermodynamics.",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Science",
    chapter: "Thermodynamics",
    difficulty: "medium",
    tags: ["thermodynamics", "first-law"],
    answer:
      "ΔU = Q − W. Energy of a system is conserved; heat added equals increase in internal energy plus work done by the system.",
  }),
  sq({
    text: "The number of moles in 44 g of CO₂ (molar mass = 44 g/mol) is ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "easy",
    tags: ["moles", "chemistry"],
    answer: "1",
    fillInBlankData: { blanks: ["1"] },
  }),
  sq({
    text: "Which of the following is a noble gas?",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "easy",
    tags: ["noble-gases", "periodic-table"],
    answer: "2",
    mcqOptions: {
      options: ["Nitrogen", "Oxygen", "Argon", "Fluorine"],
      correctAnswer: 2,
    },
  }),
  sq({
    text: "Boyle's Law states that at constant temperature, the pressure of a gas is inversely proportional to its ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Science",
    chapter: "Thermodynamics",
    difficulty: "easy",
    tags: ["Boyle's-law", "gas-laws"],
    answer: "volume",
    fillInBlankData: { blanks: ["volume"] },
  }),
  sq({
    text: "Define scalar and vector quantities and give two examples of each.",
    questionType: "short-answer",
    marks: 4,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Science",
    chapter: "Motion in a Straight Line",
    difficulty: "easy",
    tags: ["scalar", "vector", "kinematics"],
    answer:
      "Scalar: magnitude only. Examples: speed, mass. Vector: magnitude + direction. Examples: velocity, force.",
  }),
  sq({
    text: "A body of mass 5 kg is acted upon by a force of 20 N. Find its acceleration.",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Science",
    chapter: "Laws of Motion",
    difficulty: "easy",
    tags: ["Newton's-laws", "acceleration"],
    answer: "a = F/m = 20/5 = 4 m/s²",
    numericalData: { unit: "m/s²" },
  }),
  // Mathematics
  sq({
    text: "Find the value of sin 75°.",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Mathematics",
    chapter: "Introduction to Trigonometry",
    difficulty: "medium",
    tags: ["trigonometry", "compound-angles"],
    answer: "sin 75° = sin(45°+30°) = (√6+√2)/4",
  }),
  sq({
    text: "The number of ways to arrange 5 people in a row is ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Mathematics",
    chapter: "Statistics",
    difficulty: "easy",
    tags: ["permutations", "factorial"],
    answer: "120",
    fillInBlankData: { blanks: ["120"] },
  }),
  sq({
    text: "Find the slope of the line passing through (2, 3) and (4, 7).",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Mathematics",
    chapter: "Coordinate Geometry",
    difficulty: "easy",
    tags: ["coordinate-geometry", "slope"],
    answer: "m = (7−3)/(4−2) = 4/2 = 2",
  }),
  sq({
    text: "Expand (x + y)³ using the Binomial theorem.",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "medium",
    tags: ["binomial-theorem"],
    answer: "(x + y)³ = x³ + 3x²y + 3xy² + y³",
  }),
  sq({
    text: "If A = {1,2,3} and B = {2,3,4}, find A ∪ B and A ∩ B.",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "easy",
    tags: ["sets", "union", "intersection"],
    answer: "A ∪ B = {1,2,3,4}. A ∩ B = {2,3}.",
  }),
  sq({
    text: "The domain of f(x) = 1/(x−3) is all real numbers except ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "easy",
    tags: ["functions", "domain"],
    answer: "3",
    fillInBlankData: { blanks: ["3"] },
  }),
  // Computer Science
  sq({
    text: "What is the difference between a compiler and an interpreter?",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Computer Science",
    chapter: "Programming with Python/Scratch",
    difficulty: "medium",
    tags: ["compiler", "interpreter"],
    answer:
      "Compiler: translates whole program at once before execution. Interpreter: translates line-by-line during execution. Python uses interpreter; C uses compiler.",
  }),
  sq({
    text: "In Python, a list is mutable while a tuple is ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Computer Science",
    chapter: "Programming with Python/Scratch",
    difficulty: "easy",
    tags: ["Python", "list", "tuple"],
    answer: "immutable",
    fillInBlankData: { blanks: ["immutable"] },
  }),
  sq({
    text: "What is the output of: print(type(5/2)) in Python 3?",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Computer Science",
    chapter: "Programming with Python/Scratch",
    difficulty: "medium",
    tags: ["Python", "data-types"],
    answer: "1",
    mcqOptions: {
      options: ["<class 'int'>", "<class 'float'>", "<class 'str'>", "Error"],
      correctAnswer: 1,
    },
  }),
  // Social Science / Economics
  sq({
    text: "The study of individual economic units like households and firms is called ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Social Science",
    chapter: "Understanding Economic Development",
    difficulty: "easy",
    tags: ["microeconomics", "economics"],
    answer: "Microeconomics",
    fillInBlankData: { blanks: ["Microeconomics"] },
  }),
  sq({
    text: "What is GDP? How does it differ from GNP?",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 11",
    subject: "Social Science",
    chapter: "Understanding Economic Development",
    difficulty: "medium",
    tags: ["GDP", "GNP", "economics"],
    answer:
      "GDP: total value of goods/services produced within a country's borders in a year. GNP = GDP + income from abroad − income paid to foreigners.",
  }),
];

// ─── STANDARD 12 ───────────────────────────────────────────────────────────
export const std12Questions: Question[] = [
  // Science - Physics
  sq({
    text: "State Faraday's law of electromagnetic induction.",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Science",
    chapter: "Magnetic Effects",
    difficulty: "medium",
    tags: ["Faraday", "electromagnetic-induction"],
    answer:
      "The induced EMF in a circuit is directly proportional to the rate of change of magnetic flux. EMF = −dΦ/dt.",
  }),
  sq({
    text: "The work function of a metal is 2 eV. Calculate the threshold frequency. (h = 6.626 × 10⁻³⁴ J·s)",
    questionType: "numerical",
    marks: 3,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Science",
    chapter: "Modern Physics",
    difficulty: "hard",
    tags: ["photoelectric-effect", "modern-physics"],
    answer: "ν₀ = W/h = (2 × 1.6×10⁻¹⁹)/(6.626×10⁻³⁴) ≈ 4.83 × 10¹⁴ Hz",
    numericalData: { unit: "Hz" },
  }),
  sq({
    text: "In a p-n junction diode, the depletion region forms at the ______ of the junction.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Science",
    chapter: "Modern Physics",
    difficulty: "easy",
    tags: ["p-n-junction", "semiconductor"],
    answer: "interface",
    fillInBlankData: { blanks: ["interface"] },
  }),
  sq({
    text: "Define electric field intensity and state its SI unit.",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Science",
    chapter: "Electrostatics",
    difficulty: "easy",
    tags: ["electric-field", "electrostatics"],
    answer:
      "Electric field intensity = force per unit positive test charge placed at that point. E = F/q. SI unit: N/C (or V/m).",
  }),
  sq({
    text: "Two parallel conductors carrying current in the same direction ______ each other.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Science",
    chapter: "Magnetic Effects",
    difficulty: "medium",
    tags: ["magnetic-force", "current"],
    answer: "attract",
    fillInBlankData: { blanks: ["attract"] },
  }),
  sq({
    text: "What is the principle of a transformer? Give the turns ratio formula.",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Science",
    chapter: "Magnetic Effects",
    difficulty: "medium",
    tags: ["transformer", "electromagnetic-induction"],
    answer:
      "A transformer works on electromagnetic induction. Turns ratio: V₁/V₂ = N₁/N₂. Step-up: N₂ > N₁. Step-down: N₂ < N₁.",
  }),
  // Mathematics
  sq({
    text: "Find the derivative of f(x) = x³ − 4x² + 5x − 2.",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "easy",
    tags: ["calculus", "differentiation"],
    answer: "f'(x) = 3x² − 8x + 5",
  }),
  sq({
    text: "Evaluate: ∫(2x + 3)dx",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "easy",
    tags: ["integration", "calculus"],
    answer: "∫(2x+3)dx = x² + 3x + C",
  }),
  sq({
    text: "The inverse of a 2×2 matrix exists only when its determinant is ______ zero.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "medium",
    tags: ["matrices", "determinant"],
    answer: "not equal to (non-zero)",
    fillInBlankData: { blanks: ["not equal to"] },
  }),
  sq({
    text: "Two events A and B are mutually exclusive if P(A ∩ B) = ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Mathematics",
    chapter: "Probability",
    difficulty: "easy",
    tags: ["probability", "mutually-exclusive"],
    answer: "0",
    fillInBlankData: { blanks: ["0"] },
  }),
  sq({
    text: "Find the area enclosed between y = x² and y = x using integration.",
    questionType: "numerical",
    marks: 4,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "hard",
    tags: ["integration", "area", "calculus"],
    answer:
      "Intersection: x²=x → x=0,1. Area = ∫₀¹(x−x²)dx = [x²/2 − x³/3]₀¹ = 1/2 − 1/3 = 1/6 sq. units",
  }),
  sq({
    text: "If A and B are square matrices of the same order, then (AB)' = ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "medium",
    tags: ["matrices", "transpose"],
    answer: "B'A'",
    fillInBlankData: { blanks: ["B'A'"] },
  }),
  // Computer Science
  sq({
    text: "What is a primary key in a relational database?",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Computer Science",
    chapter: "Database Management",
    difficulty: "easy",
    tags: ["primary-key", "database", "SQL"],
    answer:
      "A primary key uniquely identifies each row in a table. It cannot be NULL and must be unique.",
  }),
  sq({
    text: "Write a Python function to find the factorial of n using recursion.",
    questionType: "short-answer",
    marks: 4,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Computer Science",
    chapter: "Algorithms & Problem Solving",
    difficulty: "medium",
    tags: ["recursion", "factorial", "Python"],
    answer:
      "def factorial(n):\n    if n <= 1: return 1\n    return n * factorial(n-1)",
  }),
  sq({
    text: "The OSI model has ______ layers.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Computer Science",
    chapter: "Internet & Web Technology",
    difficulty: "easy",
    tags: ["networking", "OSI-model"],
    answer: "7",
    fillInBlankData: { blanks: ["7"] },
  }),
  sq({
    text: "What is the difference between DELETE and DROP in SQL?",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Computer Science",
    chapter: "Database Management",
    difficulty: "medium",
    tags: ["SQL", "database"],
    answer:
      "DELETE removes rows from a table (table structure remains). DROP removes the entire table including its structure from the database.",
  }),
  // English
  sq({
    text: "Write a speech on 'Climate Change: Our Responsibility' for a school assembly (200 words).",
    questionType: "long-answer",
    marks: 6,
    board: "CBSE",
    standard: "Standard 12",
    subject: "English",
    chapter: "Writing - Essays",
    difficulty: "medium",
    tags: ["speech", "climate-change", "writing"],
    answer:
      "Evaluate for: salutation, clear introduction, causes & effects of climate change, individual responsibility, strong conclusion. Check grammar and vocabulary.",
  }),
  sq({
    text: "What is a precis? How is it different from a summary?",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 12",
    subject: "English",
    chapter: "Reading Comprehension",
    difficulty: "medium",
    tags: ["precis", "summary", "writing"],
    answer:
      "A precis is a concise restatement of the main ideas in about 1/3 the original length, in the writer's own words. A summary may be less strict in length and may include personal interpretation.",
  }),
  sq({
    text: "Identify and explain the literary device: 'Life is a journey with no fixed destination.'",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 12",
    subject: "English",
    chapter: "Literature - Prose",
    difficulty: "medium",
    tags: ["metaphor", "literary-devices"],
    answer:
      "Metaphor — life is directly compared to a journey without using 'like' or 'as'.",
  }),
  // Social Science
  sq({
    text: "What is meant by 'checks and balances' in a democratic system?",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Social Science",
    chapter: "Democratic Politics (Civics)",
    difficulty: "medium",
    tags: ["checks-and-balances", "democracy"],
    answer:
      "Checks and balances is a system where each branch of government (Legislature, Executive, Judiciary) can limit the powers of the others to prevent concentration of power.",
  }),
  sq({
    text: "Inflation is caused when demand exceeds supply in an economy. (True/False)",
    questionType: "true-false",
    marks: 1,
    board: "CBSE",
    standard: "Standard 12",
    subject: "Social Science",
    chapter: "Understanding Economic Development",
    difficulty: "easy",
    tags: ["inflation", "economics"],
    answer: "true",
    trueFalseData: { correctAnswer: true },
  }),
];
