import type { Question } from "../../state/mockData";

let _idCounter = 300;
function sq(
  partial: Omit<Question, "id" | "headingId" | "imageAttachment" | "type">,
): Question {
  return {
    id: `starter-${_idCounter++}`,
    headingId: null,
    imageAttachment: null,
    type: "Starter",
    ...partial,
  };
}

// ─── STANDARD 9 ─────────────────────────────────────────────────────────────
export const std9Questions: Question[] = [
  // Science
  sq({
    text: "Which of the following has the highest density?",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Science",
    chapter: "Properties of Solids & Liquids",
    difficulty: "easy",
    tags: ["density", "matter"],
    answer: "2",
    mcqOptions: { options: ["Wood", "Water", "Iron", "Air"], correctAnswer: 2 },
  }),
  sq({
    text: "State Newton's First Law of Motion.",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Science",
    chapter: "Laws of Motion",
    difficulty: "easy",
    tags: ["Newton's-laws", "inertia"],
    answer:
      "An object remains in its state of rest or uniform motion unless acted upon by an external force (Law of Inertia).",
  }),
  sq({
    text: "A body is thrown vertically upward with a velocity of 20 m/s. Find the maximum height. (g = 10 m/s²)",
    questionType: "numerical",
    marks: 3,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Science",
    chapter: "Motion in a Straight Line",
    difficulty: "medium",
    tags: ["kinematics", "motion"],
    answer: "v² = u² − 2gh → 0 = 400 − 20h → h = 20 m",
    numericalData: { unit: "m" },
  }),
  sq({
    text: "The universal law of gravitation was given by:",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Science",
    chapter: "Gravitation",
    difficulty: "easy",
    tags: ["gravitation", "Newton"],
    answer: "1",
    mcqOptions: {
      options: ["Galileo", "Newton", "Einstein", "Faraday"],
      correctAnswer: 1,
    },
  }),
  sq({
    text: "All matter is composed of tiny particles called ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Science",
    chapter: "Properties of Solids & Liquids",
    difficulty: "easy",
    tags: ["atoms", "matter"],
    answer: "atoms",
    fillInBlankData: { blanks: ["atoms"] },
  }),
  sq({
    text: "Differentiate between speed and velocity.",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Science",
    chapter: "Motion in a Straight Line",
    difficulty: "medium",
    tags: ["speed", "velocity"],
    answer:
      "Speed: distance per unit time (scalar). Velocity: displacement per unit time (vector — has direction).",
  }),
  sq({
    text: "Which part of the cell contains genetic information?",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "easy",
    tags: ["cell", "nucleus", "DNA"],
    answer: "2",
    mcqOptions: {
      options: ["Cell wall", "Mitochondria", "Nucleus", "Ribosome"],
      correctAnswer: 2,
    },
  }),
  sq({
    text: "Sound cannot travel through vacuum. (True/False)",
    questionType: "true-false",
    marks: 1,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Science",
    chapter: "Oscillations & Waves",
    difficulty: "easy",
    tags: ["sound", "waves"],
    answer: "true",
    trueFalseData: { correctAnswer: true },
  }),
  // Mathematics
  sq({
    text: "Which of the following is an irrational number?",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "easy",
    tags: ["irrational-numbers"],
    answer: "2",
    mcqOptions: { options: ["4/5", "√9", "√2", "0.25"], correctAnswer: 2 },
  }),
  sq({
    text: "Find the remainder when p(x) = x³ + 3x² + 3x + 1 is divided by (x + 1).",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Mathematics",
    chapter: "Polynomials",
    difficulty: "medium",
    tags: ["remainder-theorem", "polynomials"],
    answer: "Substitute x = −1: −1 + 3 − 3 + 1 = 0. Remainder = 0.",
  }),
  sq({
    text: "The point (−3, 4) lies in which quadrant?",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Mathematics",
    chapter: "Coordinate Geometry",
    difficulty: "easy",
    tags: ["coordinate-geometry", "quadrants"],
    answer: "1",
    mcqOptions: {
      options: ["Quadrant I", "Quadrant II", "Quadrant III", "Quadrant IV"],
      correctAnswer: 1,
    },
  }),
  sq({
    text: "In a parallelogram, opposite angles are ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Mathematics",
    chapter: "Triangles",
    difficulty: "easy",
    tags: ["parallelogram", "geometry"],
    answer: "equal",
    fillInBlankData: { blanks: ["equal"] },
  }),
  sq({
    text: "Find the mean of: 12, 15, 18, 20, 25.",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Mathematics",
    chapter: "Statistics",
    difficulty: "easy",
    tags: ["mean", "statistics"],
    answer: "Mean = (12+15+18+20+25)/5 = 90/5 = 18",
  }),
  sq({
    text: "State the Pythagorean theorem and verify it for a 3-4-5 right triangle.",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Mathematics",
    chapter: "Triangles",
    difficulty: "medium",
    tags: ["Pythagoras", "triangles"],
    answer:
      "In a right triangle: hypotenuse² = base² + perpendicular². Verification: 3² + 4² = 9 + 16 = 25 = 5². Correct.",
  }),
  sq({
    text: "A coin is tossed twice. Find the probability of getting at least one head.",
    questionType: "numerical",
    marks: 3,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Mathematics",
    chapter: "Probability",
    difficulty: "medium",
    tags: ["probability"],
    answer:
      "Sample space = {HH, HT, TH, TT}. Favourable = {HH, HT, TH} = 3. P = 3/4",
  }),
  // English
  sq({
    text: "Change to reported speech: He said, 'I am going to school.'",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 9",
    subject: "English",
    chapter: "Grammar - Voice & Narration",
    difficulty: "medium",
    tags: ["reported-speech", "narration"],
    answer: "He said that he was going to school.",
  }),
  sq({
    text: "Write an essay on 'The Importance of Education' in about 150 words.",
    questionType: "long-answer",
    marks: 6,
    board: "CBSE",
    standard: "Standard 9",
    subject: "English",
    chapter: "Writing - Essays",
    difficulty: "medium",
    tags: ["essay", "education"],
    answer:
      "Evaluate for: introduction, body (benefits of education), conclusion, grammar, vocabulary.",
  }),
  sq({
    text: "Identify the figure of speech: 'The stars danced in the night sky.'",
    questionType: "short-answer",
    marks: 1,
    board: "CBSE",
    standard: "Standard 9",
    subject: "English",
    chapter: "Literature - Prose",
    difficulty: "medium",
    tags: ["personification", "figure-of-speech"],
    answer: "Personification — stars given the human quality of dancing.",
  }),
  // Social Science
  sq({
    text: "The French Revolution took place in the year:",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Social Science",
    chapter: "Our Pasts (History)",
    difficulty: "easy",
    tags: ["French-revolution"],
    answer: "2",
    mcqOptions: { options: ["1776", "1800", "1789", "1815"], correctAnswer: 2 },
  }),
  sq({
    text: "Name the three branches of the Indian government and their functions.",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Social Science",
    chapter: "Democratic Politics (Civics)",
    difficulty: "medium",
    tags: ["government", "legislature", "executive", "judiciary"],
    answer:
      "Legislature (makes laws), Executive (implements laws), Judiciary (interprets laws and settles disputes).",
  }),
  sq({
    text: "What is sustainable development?",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Social Science",
    chapter: "Understanding Economic Development",
    difficulty: "medium",
    tags: ["sustainable-development"],
    answer:
      "Development that meets current needs without compromising future generations' ability to meet their needs.",
  }),
  // Computer Science
  sq({
    text: "An algorithm is a step-by-step set of instructions to solve a problem. (True/False)",
    questionType: "true-false",
    marks: 1,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Computer Science",
    chapter: "Algorithms & Problem Solving",
    difficulty: "easy",
    tags: ["algorithm", "programming"],
    answer: "true",
    trueFalseData: { correctAnswer: true },
  }),
  sq({
    text: "In a flowchart, a ______ shape is used for decisions.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 9",
    subject: "Computer Science",
    chapter: "Algorithms & Problem Solving",
    difficulty: "easy",
    tags: ["flowchart", "decision"],
    answer: "diamond (rhombus)",
    fillInBlankData: { blanks: ["diamond"] },
  }),
];

// ─── STANDARD 10 ────────────────────────────────────────────────────────────
export const std10Questions: Question[] = [
  // Science
  sq({
    text: "Which of the following is NOT a greenhouse gas?",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "easy",
    tags: ["greenhouse-gas", "environment"],
    answer: "3",
    mcqOptions: {
      options: ["CO₂", "Methane", "Water vapour", "Nitrogen"],
      correctAnswer: 3,
    },
  }),
  sq({
    text: "State the law of conservation of energy.",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Science",
    chapter: "Work Energy & Power",
    difficulty: "easy",
    tags: ["energy", "conservation"],
    answer:
      "Energy cannot be created or destroyed; it can only be converted from one form to another.",
  }),
  sq({
    text: "The resistance of a conductor depends on its length, cross-sectional area, and material. (True/False)",
    questionType: "true-false",
    marks: 1,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Science",
    chapter: "Current Electricity",
    difficulty: "easy",
    tags: ["resistance", "electricity"],
    answer: "true",
    trueFalseData: { correctAnswer: true },
  }),
  sq({
    text: "Calculate the power of a device that operates at 220 V and draws a current of 5 A.",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Science",
    chapter: "Current Electricity",
    difficulty: "medium",
    tags: ["power", "electricity"],
    answer: "P = V × I = 220 × 5 = 1100 W",
    numericalData: { unit: "W" },
  }),
  sq({
    text: "What is the role of the ozone layer?",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "easy",
    tags: ["ozone", "UV-rays"],
    answer:
      "The ozone layer absorbs harmful UV radiation from the Sun, protecting life on Earth from skin cancer, eye damage, etc.",
  }),
  sq({
    text: "In sexual reproduction, the male gamete is called ______ and female gamete is called ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "easy",
    tags: ["reproduction", "gametes"],
    answer: "sperm, ovum",
    fillInBlankData: { blanks: ["sperm", "ovum"] },
  }),
  sq({
    text: "Explain the process of refraction of light with Snell's law.",
    questionType: "long-answer",
    marks: 5,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "hard",
    tags: ["refraction", "Snell's-law", "optics"],
    answer:
      "Refraction is bending of light when passing from one medium to another. Snell's law: n₁ sinθ₁ = n₂ sinθ₂. Denser medium → slower speed → bends toward normal.",
  }),
  sq({
    text: "Name the process by which ionic compounds conduct electricity in their molten or aqueous state.",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Science",
    chapter: "Current Electricity",
    difficulty: "medium",
    tags: ["electrolysis", "ionic-compounds"],
    answer:
      "Electrolysis. In molten or aqueous form, ions are free to move and carry charge, enabling conduction.",
  }),
  // Mathematics
  sq({
    text: "The roots of x² − 5x + 6 = 0 are:",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Mathematics",
    chapter: "Quadratic Equations",
    difficulty: "easy",
    tags: ["quadratic-equations", "roots"],
    answer: "0",
    mcqOptions: {
      options: ["2, 3", "−2, −3", "1, 6", "−1, −6"],
      correctAnswer: 0,
    },
  }),
  sq({
    text: "Find the 20th term of the AP: 3, 7, 11, 15, ...",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Mathematics",
    chapter: "Arithmetic Progressions",
    difficulty: "easy",
    tags: ["AP", "arithmetic-progression"],
    answer: "a = 3, d = 4. T₂₀ = 3 + 19×4 = 79",
  }),
  sq({
    text: "Prove that √2 is irrational.",
    questionType: "long-answer",
    marks: 4,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "hard",
    tags: ["irrational-numbers", "proof"],
    answer:
      "Assume √2 = p/q (lowest terms). Then p² = 2q² → p is even. Let p = 2m. Then q² = 2m² → q is also even. Contradiction (common factor 2). Hence √2 is irrational.",
  }),
  sq({
    text: "If sinθ = 3/5, find cosθ and tanθ.",
    questionType: "numerical",
    marks: 3,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Mathematics",
    chapter: "Introduction to Trigonometry",
    difficulty: "medium",
    tags: ["trigonometry", "sin", "cos", "tan"],
    answer: "cosθ = 4/5 (Pythagoras: 3²+4²=5²). tanθ = 3/4",
  }),
  sq({
    text: "The tangent to a circle is ______ to the radius at the point of contact.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Mathematics",
    chapter: "Circles",
    difficulty: "easy",
    tags: ["circles", "tangent"],
    answer: "perpendicular",
    fillInBlankData: { blanks: ["perpendicular"] },
  }),
  sq({
    text: "The volume of a sphere with radius r is ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Mathematics",
    chapter: "Surface Areas & Volumes",
    difficulty: "easy",
    tags: ["volume", "sphere"],
    answer: "(4/3)πr³",
    fillInBlankData: { blanks: ["(4/3)πr³"] },
  }),
  sq({
    text: "The median of the data 5, 3, 8, 1, 9, 6, 4 (when arranged in order) is:",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Mathematics",
    chapter: "Statistics",
    difficulty: "easy",
    tags: ["median", "statistics"],
    answer: "2",
    mcqOptions: { options: ["4", "5", "6", "8"], correctAnswer: 2 },
  }),
  // Social Science
  sq({
    text: "The Dandi March (Salt March) was led by:",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Social Science",
    chapter: "Our Pasts (History)",
    difficulty: "easy",
    tags: ["Dandi-march", "Gandhi"],
    answer: "0",
    mcqOptions: {
      options: [
        "Mahatma Gandhi",
        "Jawaharlal Nehru",
        "Subhas Chandra Bose",
        "Bal Gangadhar Tilak",
      ],
      correctAnswer: 0,
    },
  }),
  sq({
    text: "Differentiate between a federal and a unitary form of government.",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Social Science",
    chapter: "Democratic Politics (Civics)",
    difficulty: "medium",
    tags: ["federal", "unitary", "government"],
    answer:
      "Federal: power divided between centre and states (e.g. India, USA). Unitary: all power with central govt (e.g. UK, France).",
  }),
  sq({
    text: "Globalisation refers to the integration of economies, societies, and cultures worldwide. (True/False)",
    questionType: "true-false",
    marks: 1,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Social Science",
    chapter: "Understanding Economic Development",
    difficulty: "easy",
    tags: ["globalisation"],
    answer: "true",
    trueFalseData: { correctAnswer: true },
  }),
  // English
  sq({
    text: "Write a letter to the editor of a newspaper complaining about poor sanitation in your locality.",
    questionType: "long-answer",
    marks: 5,
    board: "CBSE",
    standard: "Standard 10",
    subject: "English",
    chapter: "Writing - Letters & Applications",
    difficulty: "medium",
    tags: ["letter-to-editor", "writing"],
    answer:
      "Evaluate for: correct format, formal language, specific complaints, suggestions, correct closing.",
  }),
  sq({
    text: "By this time tomorrow, she ______ (complete) her project. (Use correct tense.)",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 10",
    subject: "English",
    chapter: "Grammar - Tenses",
    difficulty: "medium",
    tags: ["future-perfect", "tenses"],
    answer: "will have completed",
    fillInBlankData: { blanks: ["will have completed"] },
  }),
  // Computer Science
  sq({
    text: "The full form of HTML is:",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Computer Science",
    chapter: "Internet & Web Technology",
    difficulty: "easy",
    tags: ["HTML", "web"],
    answer: "0",
    mcqOptions: {
      options: [
        "HyperText Markup Language",
        "High Text Machine Language",
        "HyperTransfer Markup Language",
        "HighText Multilevel Language",
      ],
      correctAnswer: 0,
    },
  }),
  sq({
    text: "In Python, the function used to display output is ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Computer Science",
    chapter: "Programming with Python/Scratch",
    difficulty: "easy",
    tags: ["Python", "programming"],
    answer: "print()",
    fillInBlankData: { blanks: ["print()"] },
  }),
  sq({
    text: "What is cyberbullying? State two ways to stay safe online.",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 10",
    subject: "Computer Science",
    chapter: "Cyber Safety & Ethics",
    difficulty: "easy",
    tags: ["cyberbullying", "cyber-safety"],
    answer:
      "Cyberbullying: using digital tech to harass others. Safe practices: (1) Never share personal info online. (2) Report and block abusive users.",
  }),
];
