import type { Question } from "../../state/mockData";

let _idCounter = 100;
function sq(
  partial: Omit<Question, "id" | "headingId" | "imageAttachment" | "type">,
): Question {
  return {
    id: `starter-${_idCounter++}`,
    headingId: null,
    imageAttachment: null,
    type: "Starter",
    ...partial,
  };
}

// ─── STANDARD 6 ─────────────────────────────────────────────────────────────
export const std6Questions: Question[] = [
  // Science
  sq({
    text: "Which of the following is NOT a characteristic of living things?",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "easy",
    tags: ["living-things"],
    answer: "2",
    mcqOptions: {
      options: ["Growth", "Reproduction", "Rusting", "Respiration"],
      correctAnswer: 2,
    },
  }),
  sq({
    text: "The process by which green plants make their own food is called ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "easy",
    tags: ["photosynthesis"],
    answer: "Photosynthesis",
    fillInBlankData: { blanks: ["Photosynthesis"] },
  }),
  sq({
    text: "The Earth is the only planet in the solar system known to have life. (True/False)",
    questionType: "true-false",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "easy",
    tags: ["solar-system"],
    answer: "true",
    trueFalseData: { correctAnswer: true },
  }),
  sq({
    text: "What are the three states of matter? Give one example of each.",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Science",
    chapter: "Properties of Solids & Liquids",
    difficulty: "easy",
    tags: ["states-of-matter"],
    answer: "Solid (ice), Liquid (water), Gas (steam).",
  }),
  sq({
    text: "A magnet has ______ poles.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Science",
    chapter: "Magnetic Effects",
    difficulty: "easy",
    tags: ["magnets"],
    answer: "two",
    fillInBlankData: { blanks: ["two"] },
  }),
  sq({
    text: "Which organ pumps blood throughout the body?",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "easy",
    tags: ["heart", "biology"],
    answer: "1",
    mcqOptions: {
      options: ["Lungs", "Heart", "Kidneys", "Liver"],
      correctAnswer: 1,
    },
  }),
  // Mathematics
  sq({
    text: "The HCF of 12 and 18 is:",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "easy",
    tags: ["HCF", "factors"],
    answer: "2",
    mcqOptions: { options: ["2", "4", "6", "9"], correctAnswer: 2 },
  }),
  sq({
    text: "Write the next three terms: 2, 4, 8, 16, __, __, __",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "easy",
    tags: ["patterns", "number-series"],
    answer: "32, 64, 128",
  }),
  sq({
    text: "A rectangle has length 8 cm and breadth 5 cm. Its perimeter is ______ cm.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Mathematics",
    chapter: "Triangles",
    difficulty: "easy",
    tags: ["perimeter", "rectangle"],
    answer: "26",
    fillInBlankData: { blanks: ["26"] },
  }),
  sq({
    text: "Solve: 3x − 7 = 11. Find x.",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Mathematics",
    chapter: "Linear Equations",
    difficulty: "easy",
    tags: ["algebra"],
    answer: "x = 6",
  }),
  sq({
    text: "A prime number has exactly two factors: 1 and itself. (True/False)",
    questionType: "true-false",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "easy",
    tags: ["prime-numbers"],
    answer: "true",
    trueFalseData: { correctAnswer: true },
  }),
  // English
  sq({
    text: "Identify the noun in: 'The dog ran across the garden.'",
    questionType: "short-answer",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "English",
    chapter: "Grammar - Parts of Speech",
    difficulty: "easy",
    tags: ["nouns", "grammar"],
    answer: "dog, garden",
  }),
  sq({
    text: "Choose the correct verb: She ______ (go/goes) to school every day.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "English",
    chapter: "Grammar - Tenses",
    difficulty: "easy",
    tags: ["verbs", "tenses"],
    answer: "goes",
    fillInBlankData: { blanks: ["goes"] },
  }),
  sq({
    text: "An adjective describes a noun. (True/False)",
    questionType: "true-false",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "English",
    chapter: "Grammar - Parts of Speech",
    difficulty: "easy",
    tags: ["adjective", "grammar"],
    answer: "true",
    trueFalseData: { correctAnswer: true },
  }),
  sq({
    text: "Write a short paragraph (4–5 sentences) describing your favourite season.",
    questionType: "long-answer",
    marks: 5,
    board: "CBSE",
    standard: "Standard 6",
    subject: "English",
    chapter: "Writing - Essays",
    difficulty: "medium",
    tags: ["writing", "descriptive"],
    answer:
      "Award marks for structure, vocabulary, grammar, and relevant content.",
  }),
  // Social Science
  sq({
    text: "The oldest civilisation in India developed near the river:",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Social Science",
    chapter: "Our Pasts (History)",
    difficulty: "easy",
    tags: ["indus-valley", "civilisation"],
    answer: "1",
    mcqOptions: {
      options: ["Ganga", "Indus", "Yamuna", "Brahmaputra"],
      correctAnswer: 1,
    },
  }),
  sq({
    text: "India is located in which continent?",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Social Science",
    chapter: "Resources & Development (Geography)",
    difficulty: "easy",
    tags: ["geography", "india"],
    answer: "1",
    mcqOptions: {
      options: ["Africa", "Asia", "Europe", "Australia"],
      correctAnswer: 1,
    },
  }),
  sq({
    text: "The Preamble of the Indian Constitution begins with 'We the People of India'. (True/False)",
    questionType: "true-false",
    marks: 1,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Social Science",
    chapter: "Democratic Politics (Civics)",
    difficulty: "easy",
    tags: ["constitution", "preamble"],
    answer: "true",
    trueFalseData: { correctAnswer: true },
  }),
  sq({
    text: "Name three main rivers of India and the states they flow through.",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 6",
    subject: "Social Science",
    chapter: "Resources & Development (Geography)",
    difficulty: "easy",
    tags: ["rivers", "geography"],
    answer:
      "Ganga (UP, Bihar), Yamuna (Delhi, UP), Brahmaputra (Assam). Accept correct answers.",
  }),
];

// ─── STANDARD 7 ─────────────────────────────────────────────────────────────
export const std7Questions: Question[] = [
  // Science
  sq({
    text: "Which of the following is a chemical change?",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Science",
    chapter: "Properties of Solids & Liquids",
    difficulty: "easy",
    tags: ["chemical-change"],
    answer: "2",
    mcqOptions: {
      options: [
        "Melting of ice",
        "Cutting of wood",
        "Burning of paper",
        "Dissolving salt in water",
      ],
      correctAnswer: 2,
    },
  }),
  sq({
    text: "The structural and functional unit of life is the ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "easy",
    tags: ["cell", "biology"],
    answer: "Cell",
    fillInBlankData: { blanks: ["Cell"] },
  }),
  sq({
    text: "Light travels faster in water than in air. (True/False)",
    questionType: "true-false",
    marks: 1,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "medium",
    tags: ["light", "speed"],
    answer: "false",
    trueFalseData: { correctAnswer: false },
  }),
  sq({
    text: "What is the difference between a conductor and an insulator? Give two examples of each.",
    questionType: "short-answer",
    marks: 4,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Science",
    chapter: "Current Electricity",
    difficulty: "medium",
    tags: ["conductor", "insulator"],
    answer:
      "Conductor: allows electric current. Examples: copper, iron. Insulator: does not allow current. Examples: rubber, plastic.",
  }),
  sq({
    text: "A concave lens always forms a virtual and ______ image.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "medium",
    tags: ["lenses", "optics"],
    answer: "diminished",
    fillInBlankData: { blanks: ["diminished"] },
  }),
  sq({
    text: "Name the gas that makes up about 78% of the Earth's atmosphere.",
    questionType: "short-answer",
    marks: 1,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "easy",
    tags: ["atmosphere", "nitrogen"],
    answer: "Nitrogen (N₂)",
  }),
  // Mathematics
  sq({
    text: "The sum of angles of a triangle is:",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Mathematics",
    chapter: "Triangles",
    difficulty: "easy",
    tags: ["triangles", "angles"],
    answer: "2",
    mcqOptions: { options: ["90°", "270°", "180°", "360°"], correctAnswer: 2 },
  }),
  sq({
    text: "Find the area of a triangle with base 10 cm and height 6 cm.",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Mathematics",
    chapter: "Triangles",
    difficulty: "easy",
    tags: ["area", "triangle"],
    answer: "Area = ½ × 10 × 6 = 30 cm²",
    numericalData: { unit: "cm²" },
  }),
  sq({
    text: "Solve: 5x + 3 = 23. Find x.",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Mathematics",
    chapter: "Linear Equations",
    difficulty: "easy",
    tags: ["algebra", "equations"],
    answer: "x = 4",
  }),
  sq({
    text: "Express 0.625 as a fraction in its lowest terms.",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "medium",
    tags: ["fractions", "decimals"],
    answer: "0.625 = 5/8",
  }),
  sq({
    text: "A negative number multiplied by a negative number gives a positive result. (True/False)",
    questionType: "true-false",
    marks: 1,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Mathematics",
    chapter: "Real Numbers",
    difficulty: "easy",
    tags: ["integers"],
    answer: "true",
    trueFalseData: { correctAnswer: true },
  }),
  // Social Science
  sq({
    text: "The Mughal emperor who built the Taj Mahal was:",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Social Science",
    chapter: "Our Pasts (History)",
    difficulty: "easy",
    tags: ["mughal", "taj-mahal"],
    answer: "1",
    mcqOptions: {
      options: ["Akbar", "Shah Jahan", "Aurangzeb", "Babur"],
      correctAnswer: 1,
    },
  }),
  sq({
    text: "Latitude and longitude are imaginary lines used to locate places on a map. (True/False)",
    questionType: "true-false",
    marks: 1,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Social Science",
    chapter: "Resources & Development (Geography)",
    difficulty: "easy",
    tags: ["latitude", "longitude"],
    answer: "true",
    trueFalseData: { correctAnswer: true },
  }),
  sq({
    text: "What is democracy? State its two main features.",
    questionType: "short-answer",
    marks: 3,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Social Science",
    chapter: "Democratic Politics (Civics)",
    difficulty: "medium",
    tags: ["democracy", "civics"],
    answer:
      "Democracy is a form of government where people elect their own representatives. Features: (1) Free and fair elections (2) Rule of law.",
  }),
  // Computer Science
  sq({
    text: "Input → Processing → ______ is the basic cycle of a computer.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Computer Science",
    chapter: "Introduction to Computing",
    difficulty: "easy",
    tags: ["computer", "IPO"],
    answer: "Output",
    fillInBlankData: { blanks: ["Output"] },
  }),
  sq({
    text: "Which of the following is an output device?",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 7",
    subject: "Computer Science",
    chapter: "Introduction to Computing",
    difficulty: "easy",
    tags: ["output-device"],
    answer: "0",
    mcqOptions: {
      options: ["Monitor", "Keyboard", "Mouse", "Scanner"],
      correctAnswer: 0,
    },
  }),
];

// ─── STANDARD 8 ─────────────────────────────────────────────────────────────
export const std8Questions: Question[] = [
  // Science
  sq({
    text: "Which gas is released during photosynthesis?",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Science",
    chapter: "Physical World",
    difficulty: "easy",
    tags: ["photosynthesis", "oxygen"],
    answer: "0",
    mcqOptions: {
      options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"],
      correctAnswer: 0,
    },
  }),
  sq({
    text: "The SI unit of force is the ______.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Science",
    chapter: "Laws of Motion",
    difficulty: "easy",
    tags: ["force", "SI-unit"],
    answer: "Newton (N)",
    fillInBlankData: { blanks: ["Newton (N)"] },
  }),
  sq({
    text: "State Newton's Second Law of Motion.",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Science",
    chapter: "Laws of Motion",
    difficulty: "medium",
    tags: ["Newton's-laws", "motion"],
    answer:
      "Force = mass × acceleration (F = ma). The force on an object equals the rate of change of its momentum.",
  }),
  sq({
    text: "Friction always opposes motion. (True/False)",
    questionType: "true-false",
    marks: 1,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Science",
    chapter: "Laws of Motion",
    difficulty: "easy",
    tags: ["friction"],
    answer: "true",
    trueFalseData: { correctAnswer: true },
  }),
  sq({
    text: "A cell converts ______ energy into ______ energy.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Science",
    chapter: "Current Electricity",
    difficulty: "easy",
    tags: ["cell", "energy"],
    answer: "chemical, electrical",
    fillInBlankData: { blanks: ["chemical", "electrical"] },
  }),
  sq({
    text: "What is meant by conservation of energy? Give one example.",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Science",
    chapter: "Work Energy & Power",
    difficulty: "easy",
    tags: ["energy", "conservation"],
    answer:
      "Energy cannot be created or destroyed; it changes form. Example: A ball falling converts potential energy to kinetic energy.",
  }),
  // Mathematics
  sq({
    text: "If a = 3 and b = −2, find the value of a² − b².",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Mathematics",
    chapter: "Polynomials",
    difficulty: "medium",
    tags: ["algebra"],
    answer: "a² − b² = 9 − 4 = 5",
  }),
  sq({
    text: "The ratio of the circumference to the diameter of a circle is:",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Mathematics",
    chapter: "Areas Related to Circles",
    difficulty: "easy",
    tags: ["circles", "pi"],
    answer: "1",
    mcqOptions: { options: ["2π", "π", "π/2", "2"], correctAnswer: 1 },
  }),
  sq({
    text: "Factorise: x² − 9",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Mathematics",
    chapter: "Polynomials",
    difficulty: "medium",
    tags: ["factorisation"],
    answer: "x² − 9 = (x + 3)(x − 3)",
  }),
  sq({
    text: "A shopkeeper bought an article for ₹800 and sold it for ₹1000. Find the profit percentage.",
    questionType: "numerical",
    marks: 3,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Mathematics",
    chapter: "Statistics",
    difficulty: "medium",
    tags: ["profit-loss", "percentage"],
    answer: "Profit = ₹200. Profit% = (200/800) × 100 = 25%",
    numericalData: { unit: "%" },
  }),
  sq({
    text: "Solve: 2(3x − 4) = 16. Find x.",
    questionType: "numerical",
    marks: 2,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Mathematics",
    chapter: "Linear Equations",
    difficulty: "easy",
    tags: ["linear-equations"],
    answer: "6x − 8 = 16 → x = 4",
  }),
  // English
  sq({
    text: "Change to passive voice: 'The teacher praised the student.'",
    questionType: "short-answer",
    marks: 2,
    board: "CBSE",
    standard: "Standard 8",
    subject: "English",
    chapter: "Grammar - Voice & Narration",
    difficulty: "medium",
    tags: ["passive-voice", "grammar"],
    answer: "The student was praised by the teacher.",
  }),
  sq({
    text: "Write a formal letter to the principal requesting one week's leave.",
    questionType: "long-answer",
    marks: 5,
    board: "CBSE",
    standard: "Standard 8",
    subject: "English",
    chapter: "Writing - Letters & Applications",
    difficulty: "medium",
    tags: ["formal-letter", "writing"],
    answer:
      "Evaluate for: proper format, formal language, clear reason, polite tone, correct closing.",
  }),
  // Social Science
  sq({
    text: "The Indian National Congress was founded in:",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Social Science",
    chapter: "Our Pasts (History)",
    difficulty: "easy",
    tags: ["INC", "freedom-struggle"],
    answer: "2",
    mcqOptions: { options: ["1857", "1875", "1885", "1905"], correctAnswer: 2 },
  }),
  sq({
    text: "What are natural resources? Give two examples each of renewable and non-renewable resources.",
    questionType: "short-answer",
    marks: 4,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Social Science",
    chapter: "Resources & Development (Geography)",
    difficulty: "medium",
    tags: ["natural-resources", "renewable"],
    answer:
      "Natural resources are gifts of nature (land, water, forests). Renewable: solar energy, wind energy. Non-renewable: coal, petroleum.",
  }),
  // Computer Science
  sq({
    text: "The full form of CPU is:",
    questionType: "mcq",
    marks: 1,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Computer Science",
    chapter: "Introduction to Computing",
    difficulty: "easy",
    tags: ["CPU", "hardware"],
    answer: "0",
    mcqOptions: {
      options: [
        "Central Processing Unit",
        "Computer Personal Unit",
        "Central Program Unit",
        "Control Processing Unit",
      ],
      correctAnswer: 0,
    },
  }),
  sq({
    text: "RAM stands for ______ and it is ______ memory.",
    questionType: "fill-in-blank",
    marks: 1,
    board: "CBSE",
    standard: "Standard 8",
    subject: "Computer Science",
    chapter: "Introduction to Computing",
    difficulty: "easy",
    tags: ["RAM", "memory"],
    answer: "Random Access Memory, volatile",
    fillInBlankData: { blanks: ["Random Access Memory", "volatile"] },
  }),
];
